// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8zrWhGDCcK1cD6ktccEfzZ7kQm3FzckE',
    appId: '1:116834294360:web:a452cf2cd029165298c82d',
    messagingSenderId: '116834294360',
    projectId: 'flutter-firebase-a03f3',
    authDomain: 'flutter-firebase-a03f3.firebaseapp.com',
    storageBucket: 'flutter-firebase-a03f3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCglwewa23F0MJS8B6NZDHdv4CnAFD9Drg',
    appId: '1:116834294360:android:59265c8d93a4fa1f98c82d',
    messagingSenderId: '116834294360',
    projectId: 'flutter-firebase-a03f3',
    storageBucket: 'flutter-firebase-a03f3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiZAlprtzbc67i3psshcLNCDEsak_fyFs',
    appId: '1:116834294360:ios:466406a1750205ec98c82d',
    messagingSenderId: '116834294360',
    projectId: 'flutter-firebase-a03f3',
    storageBucket: 'flutter-firebase-a03f3.appspot.com',
    iosBundleId: 'com.example.authentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiZAlprtzbc67i3psshcLNCDEsak_fyFs',
    appId: '1:116834294360:ios:f498d538bf53069198c82d',
    messagingSenderId: '116834294360',
    projectId: 'flutter-firebase-a03f3',
    storageBucket: 'flutter-firebase-a03f3.appspot.com',
    iosBundleId: 'com.example.authentication.RunnerTests',
  );
}
